### ISSUE TITLE
What should i do if i can't create a plugin?

### ISSUE THREAD

**Issue by Aspector1** [Martyn0324/SerpentAI#15]
* **Operating System:** Windows
* **Game:** ([link to Steam page or Game](https://store.steampowered.com/app/1687950/Persona_5_Royal/))
* **Backend:** GPU
* **An URL to your GamePlugin or GameAgentPlugin repository, if possible:**

### Expected result
Creating a game plugin

### Encountered result
```
OFFSHOOT: Attempting to install SerpentPersonaGamePlugin...

OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...


OFFSHOOT PLUGIN INSTALL: Installing files...

C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\base.py:63: UserWarning: 'serpent.game' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)
C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\base.py:63: UserWarning: 'serpent.game_agent' does not appear to be a valid module. Skipping!
  warnings.warn("'%s' does not appear to be a valid module. Skipping!" % m)

There was a problem during installation... Reverting!
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WBC\SerpentAI-dev\serpent\plugins\SerpentPersonaGamePlugin\plugin.py", line 28, in <module>
    offshoot.executable_hook(SerpentPersonaGamePlugin)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\base.py", line 185, in executable_hook
    plugin_class.install()
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 35, in install
    cls.install_files()
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 118, in install_files
    raise e
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 91, in install_files
    is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
    raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentPersonaGamePlugin\files\serpent_Persona_game.py => Game

```
### Steps to reproduce

1. Conda activate serpent
2. Serpent generate game
3. persona
4. steam

**Comment by Aspector1** [comment]
I figured it out.

**Comment by devwithilja** [comment]
Do you have a hint how to solve it?

Somehow stuck at the same point.

> (SerpentAI) C:\ilja_wp\VisualStudio\SerpentAI>serpent activate SerpentAgeofEmpires2HDGamePlugin
> OFFSHOOT: Attempting to install SerpentAgeofEmpires2HDGamePlugin...
> 
> OFFSHOOT PLUGIN INSTALL: Verifying that plugin dependencies are installed...
> 
> 
> OFFSHOOT PLUGIN INSTALL: Installing files...
> 
> 
> There was a problem during installation... Reverting!
> Traceback (most recent call last):
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\ilja_wp\VisualStudio\SerpentAI\plugins\SerpentAgeofEmpires2HDGamePlugin\plugin.py", line 28, in <module>
>     offshoot.executable_hook(SerpentAgeofEmpires2HDGamePlugin)
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\site-packages\offshoot\base.py", line 185, in executable_hook
>     plugin_class.install()
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\site-packages\offshoot\plugin.py", line 35, in install
>     cls.install_files()
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\site-packages\offshoot\plugin.py", line 118, in install_files
>     raise e
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\site-packages\offshoot\plugin.py", line 91, in install_files
>     is_valid, messages = cls._validate_file_for_pluggable(plugin_file_path, file_dict["pluggable"])
>   File "c:\ilja_programme\scoop\apps\anaconda3\current\envs\serpentai\lib\site-packages\offshoot\plugin.py", line 235, in _validate_file_for_pluggable
>     raise PluginError("The Plugin definition specifies an invalid pluggable: %s => %s" % (file_path, pluggable))
> offshoot.plugin.PluginError: The Plugin definition specifies an invalid pluggable: plugins\SerpentAgeofEmpires2HDGamePlugin\files\serpent_AgeofEmpires2HD_game.py => Game

**Comment by shadow221213** [comment]
> I figured it out.

Could you teach me how to do it?

**Comment by XliOK** [comment]
I have encountered the same problem, please guide me. Thank you very much!
