### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by Aspector1** [Martyn0324/SerpentAI#16]
* **Operating System:** Windows
* **Game:** ([link to Steam page or Game](https://store.steampowered.com/app/1687950/Persona_5_Royal/))
* **Backend:** GPU
* **An URL to your GamePlugin or GameAgentPlugin repository, if possible:**

### Expected result
Creating dataset

### Encountered result
```
PAUSED

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 380, in record
    frame_spacing=int(frame_spacing)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 202, in play
    raise e
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 198, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 124, in on_pause
    on_frame_handler_pause(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 310, in on_record_pause
    active_keys.remove(key_name)
KeyError: 'KEY_LEFT_ALT'

```

### Steps to reproduce

1. serpent record persona serpentpersonagameagent
2. alt + tab to anaconda prompt

**Comment by Aspector1** [comment]
Can you help me, please?

**Comment by Aspector1** [comment]
Got a new error:
```
Writing Recorded Input Data to 'datasets/input_recording.h5'... (1/65)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 380, in record
    frame_spacing=int(frame_spacing)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 202, in play
    raise e
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 198, in play
    game_agent.on_pause(frame_handler=frame_handler, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 124, in on_pause
    on_frame_handler_pause(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 336, in on_record_pause
    data=[game_frame.frame_bytes for game_frame in game_frame_buffer.frames]
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by Aspector1** [comment]
No, I got the old one, again.

**Comment by Martyn0324** [comment]
```
File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 310, in on_record_pause
    active_keys.remove(key_name)
KeyError: 'KEY_LEFT_ALT'
```

It might be possible that, when you use alt+tab, Serpent tries to record those inputs, but fails doing so, which throws an error.

Try defining a pause function using another key

**Comment by Aspector1** [comment]
> ```
> File "C:\ProgramData\Anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 310, in on_record_pause
>     active_keys.remove(key_name)
> KeyError: 'KEY_LEFT_ALT'
> ```
> 
> It might be possible that, when you use alt+tab, Serpent tries to record those inputs, but fails doing so, which throws an error.
> 
> Try defining a pause function using another key

I tried to run the game in a window and then just move the focus to the anaconda with the mouse, but then I got the last error that I wrote, that one with h5py

**Comment by Martyn0324** [comment]
It seems that h5py is either receiving frames with different shapes(which I guess it's unlikely) or it's receiving frames with different data types(one type can be int32 and another can be float32 for example).

Try making sure that your frames are all on the same type with `.astype('')` and check your frame sizes. If the game window size gets smaller during recording, perhaps serpent start capturing that smaller frame which throws an error in h5py.

**Comment by Aspector1** [comment]
> It seems that h5py is either receiving frames with different shapes(which I guess it's unlikely) or it's receiving frames with different data types(one type can be int32 and another can be float32 for example).
> 
> Try making sure that your frames are all on the same type with `.astype('')` and check your frame sizes. If the game window size gets smaller during recording, perhaps serpent start capturing that smaller frame which throws an error in h5py.

I'm just beginning to research SerpentAI and I don't know anything about its settings. I'm following this [video](https://youtu.be/hIFkdao0ELU). The only thing I can say about the settings is that I set the resolution to 960x540 for SerpentAI.

My video:

https://user-images.githubusercontent.com/84536195/198279139-36762b15-94f7-4820-9bcc-adbe8ec0bf92.mp4
